defaultPlacement: end
enableVersioning: true
entryTypes:
  - d43220af-ee7e-4bc5-8482-2374c8815aca # Homepage
handle: homepage
maxAuthors: 2
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5d346946-3841-458d-9ae1-08b4e10bf8fe: # English
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
  9155b977-ae75-4e7e-aa57-cfcd0453780e: # RetroSpin-Records
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
