defaultPlacement: end
enableVersioning: true
entryTypes:
  - ed333ccf-fb85-4fd6-a36a-df827218fef4 # Winkelmand
handle: winkelmand
maxAuthors: 1
name: Winkelmand
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9155b977-ae75-4e7e-aa57-cfcd0453780e: # RetroSpin-Records
    enabledByDefault: true
    hasUrls: true
    template: error404.twig
    uriFormat: winkelmand
type: single
