baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: nl
name: RetroSpin-Records
primary: true
siteGroup: 6bbad967-7648-4693-aa58-3ff8c708520b # RetroSpin-Records
sortOrder: 1
