altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c2cb96e9-3907-4ea4-8345-d2c7ee31b271:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3ca6b8ae-9cda-47d7-a767-f1393f255295
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3cb4a414-013c-4faa-8494-c0f8e55c98af
        userCondition: null
fs: bestanden
handle: bestanden
name: Bestanden
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
