color: emerald
fieldLayouts:
  dd608f51-962b-4d44-a4ab-d91396d93905:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc71ea0d-543c-4541-bc83-5383c5497aa6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e240ab47-60dd-4276-a6d9-652f040e5769 # text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 960226b0-4adf-4110-a831-41f039549034
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cadc980-a6c8-47f1-92b8-5964fb4a57fe # NavImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77b5f3a7-b001-4493-81f3-aead4a45fb3c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8bef58e4-9a72-4276-8a40-44dc15a4d07e
        userCondition: null
handle: contact
hasTitleField: true
icon: address-book
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
