color: cyan
fieldLayouts:
  cc95c42a-7eb4-4010-817a-6dac9ee2d1e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9aa8635f-f750-416f-9523-c84a2ab55317
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cadc980-a6c8-47f1-92b8-5964fb4a57fe # NavImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a07d44cf-3de9-41cc-bcca-f539d6cdce60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46ea303c-cde5-4342-9af9-0be10c3ea3f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e89feea-4ffc-4c6f-9841-80f56d7170fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98df6770-ea08-4390-b90a-c5d5634caaac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7009ad-02cd-4079-9976-93a27f92259f # ProductPrijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74a97f9a-786e-40b2-8f2f-6df78fa004e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7790ae66-c72f-4345-8a12-d79cb11d673f # test
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a837978-5436-4dda-bdf4-69d52d9b4c0c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85c71c50-7a1c-446d-8c4d-265f73760700
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: producttitle2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5d7995b-fc1b-431c-84f0-ec1d4996e6c1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: productimage2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d379a27-a2b2-433c-87ef-39e46597ec35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: productdescription2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7133439-1310-4423-a4d4-31358166e2a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7009ad-02cd-4079-9976-93a27f92259f # ProductPrijs
            handle: productprijs2
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a19eafa0-8226-410c-8dd4-9623f32b560d
            userCondition: null
            warning: null
            width: 100
        name: product2
        uid: 533ec913-0a72-4679-8265-82d77a4c8011
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: producttitle3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 413fd01f-0dec-43ff-bac8-b7e65037ae59
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: productimage3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88b10cb0-d912-452b-8ffb-c17b9df4bdcb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: productdescription3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ffd1313-24f7-4dc4-802d-69a59257f063
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7009ad-02cd-4079-9976-93a27f92259f # ProductPrijs
            handle: productprijs3
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca8bf8f4-cba8-49bb-a79d-82cf93b1876f
            userCondition: null
            warning: null
            width: 100
        name: product3
        uid: 3056fe3b-1786-4d13-ad43-86f0bc191cc0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: producttitle4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23906e17-5f5b-4f02-a2cf-052825050e15
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: productimage4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1ac8b3c-7111-4640-b2b1-4d328ccba413
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: productdescription4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca935efb-b75a-48e5-a36e-3a940101dec1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7009ad-02cd-4079-9976-93a27f92259f # ProductPrijs
            handle: productprijs4
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdb8d2bd-0d72-43f8-9637-17de083601e0
            userCondition: null
            warning: null
            width: 100
        name: product4
        uid: 7ca77cb3-6470-44b2-9af4-77f2fa6aa8cc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: producttitle5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9007d1b-809e-47d2-bd85-5bc482792cae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: productimage5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aee4c67c-80f5-4eb7-9ac0-a0ee2c824712
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: productdescription5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea2e07aa-08ef-4f91-a150-1be975dca8fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7009ad-02cd-4079-9976-93a27f92259f # ProductPrijs
            handle: productprijs5
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 657ae9bb-1660-4496-94ad-8210b18760c2
            userCondition: null
            warning: null
            width: 100
        name: product5
        uid: 2e666c71-5666-4139-a899-23873c273391
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: producttitle6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c4c0f22-7aff-4cb8-89e3-f87b07ac94a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: productimage6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fcac588f-d07f-43cc-8a97-e8c48585416a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: productdescription6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a901d1a4-47e5-430d-8c8c-2728a19030cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5c7009ad-02cd-4079-9976-93a27f92259f # ProductPrijs
            handle: productprijs6
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71a65528-85ff-4b62-9558-488bd42b4041
            userCondition: null
            warning: null
            width: 100
        name: product6
        uid: cff3dca9-fcc7-4d77-acfe-33cae66cf491
        userCondition: null
handle: producten
hasTitleField: true
icon: album-collection
name: Producten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
