color: cyan
fieldLayouts:
  cc95c42a-7eb4-4010-817a-6dac9ee2d1e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9aa8635f-f750-416f-9523-c84a2ab55317
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0cadc980-a6c8-47f1-92b8-5964fb4a57fe # NavImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a07d44cf-3de9-41cc-bcca-f539d6cdce60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f94e0e22-1784-4adf-aeb5-2e1084448eb3 # ProductTitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46ea303c-cde5-4342-9af9-0be10c3ea3f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8435c819-c72b-466f-a620-16ba7f8654fc # ProductImage
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e89feea-4ffc-4c6f-9841-80f56d7170fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a3afe43-ff07-4247-9e9b-d0d60572a7f8 # ProductDescription
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98df6770-ea08-4390-b90a-c5d5634caaac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85c71c50-7a1c-446d-8c4d-265f73760700
        userCondition: null
handle: producten
hasTitleField: true
icon: album-collection
name: Producten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
