color: cyan
fieldLayouts:
  cc95c42a-7eb4-4010-817a-6dac9ee2d1e2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9aa8635f-f750-416f-9523-c84a2ab55317
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85c71c50-7a1c-446d-8c4d-265f73760700
        userCondition: null
handle: producten
hasTitleField: true
icon: album-collection
name: Producten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
