dateModified: 1713879586
email:
  fromEmail: thomas.peeters3@student.pxl.be
  fromName: RetroSpin-Records
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    6bbad967-7648-4693-aa58-3ff8c708520b: RetroSpin-Records # RetroSpin-Records
    9155b977-ae75-4e7e-aa57-cfcd0453780e: RetroSpin-Records # RetroSpin-Records
system:
  edition: solo
  live: true
  name: RetroSpin-Records
  schemaVersion: 5.0.0.20
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
